openapi: 3.1.0
info:
  title: Hotel Booking API
  version: 1.0.0
  description: API for hotel, room, booking, and user management
servers:
  - url: http://localhost:3000/
    description: Local server
tags:
  - name: Auth
  - name: Hotels
  - name: Rooms
  - name: Bookings
  - name: Users
paths:
  /api/auth/signup:
    post:
      tags:
        - Auth
      summary: User signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created
        '400':
          $ref: '#/components/responses/ErrorResponse'
  /api/auth/login:
    post:
      tags:
        - Auth
      summary: User login
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /api/hotels:
    post:
      tags:
        - Hotels
      summary: Create hotel (Admin)
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Hotel created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hotel'
  /api/admin/hotels:
    get:
      tags:
        - Hotels
      summary: Get all hotels (Admin)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of hotels
  /api/owner/hotels:
    get:
      tags:
        - Hotels
      summary: Get hotels owned by current owner
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Owner hotels
  /api/hotels/{id}:
    patch:
      tags:
        - Hotels
      summary: Update hotel (Admin/Owner)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Hotel updated
    delete:
      tags:
        - Hotels
      summary: Delete hotel (Admin)
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Hotel deleted
  /api/hotels/{hotelId}/rooms:
    post:
      tags:
        - Rooms
      summary: Create room under a hotel (Admin/Owner)
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Room created
  /api/rooms:
    get:
      tags:
        - Rooms
      summary: Get all rooms (public)
      responses:
        '200':
          description: Room list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Room'
  /api/rooms/{id}:
    get:
      tags:
        - Rooms
      summary: Get room by ID
      responses:
        '200':
          description: Room details
    patch:
      tags:
        - Rooms
      summary: Update room (Admin/Owner)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Room updated
    delete:
      tags:
        - Rooms
      summary: Delete room (Admin/Owner)
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Room deleted
  /api/bookings:
    post:
      tags:
        - Bookings
      summary: Create booking (Guest)
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Booking created
    get:
      tags:
        - Bookings
      summary: Get user's own bookings
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User bookings
  /api/bookings/{id}:
    patch:
      tags:
        - Bookings
      summary: Update booking (Guest)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Booking updated
    delete:
      tags:
        - Bookings
      summary: Delete booking (Admin)
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Booking deleted
  /api/owner/bookings:
    get:
      tags:
        - Bookings
      summary: Get bookings for owner’s hotels
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Owner bookings
  /api/admin/bookings:
    get:
      tags:
        - Bookings
      summary: Admin get all bookings
      security:
        - bearerAuth: []
      responses:
        '200':
          description: All bookings
  /api/admin/users:
    get:
      tags:
        - Users
      summary: Get all users (Admin)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of users
  /api/owner/hotels/{hotelId}/guests:
    get:
      tags:
        - Users
      summary: Get guests who booked rooms in owner's hotel
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Guest list
  /api/users/me:
    patch:
      tags:
        - Users
      summary: Update own profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profile updated
    delete:
      tags:
        - Users
      summary: Delete own account
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Account deleted
components:
  schemas:
    Hotel:
      Hotel:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
          city:
            type: string
          address:
            type: string
          rating:
            type: number
          ownerId:
            type: integer
            nullable: true
    Room:
      Room:
        type: object
        properties:
          id:
            type: integer
          roomNumber:
            type: string
          capacity:
            type: integer
          pricePerNight:
            type: number
          amenities:
            type: array
            items:
              type: string
          hotel:
            $ref: ../schemas/Hotel.yaml#/Hotel
    Booking:
      Booking:
        type: object
        properties:
          id:
            type: integer
          roomId:
            type: integer
          userId:
            type: integer
          startDate:
            type: string
            format: date
          endDate:
            type: string
            format: date
          guests:
            type: integer
          total:
            type: number
          status:
            type: string
            enum:
              - BOOKED
              - CANCELED
    User:
      User:
        type: object
        properties:
          id:
            type: integer
          name:
            type: string
          email:
            type: string
          role:
            type: string
            enum:
              - ADMIN
              - OWNER
              - GUEST
    LoginResponse:
      $ref: '#/components/schemas/Auth'
    Auth:
      LoginResponse:
        type: object
        properties:
          accessToken:
            type: string
          user:
            $ref: ../schemas/User.yaml#/User
  responses:
    ErrorResponse:
      ErrorResponse:
        type: object
        properties:
          message:
            type: string
    Unauthorized:
      Unauthorized:
        description: Missing or invalid token
        content:
          application/json:
            schema:
              $ref: ./ErrorResponse.yaml#/ErrorResponse
    Forbidden:
      Forbidden:
        description: Access denied
        content:
          application/json:
            schema:
              $ref: ./ErrorResponse.yaml#/ErrorResponse
    NotFound:
      NotFound:
        description: Resource not found
        content:
          application/json:
            schema:
              $ref: ./ErrorResponse.yaml#/ErrorResponse
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
